<?php
ini_set('default_mimetype', '');

// Récupérer le PATH_INFO depuis les variables d'environnement CGI
$path_info = getenv('PATH_INFO');

// Afficher le PATH_INFO pour débogage
fwrite(fopen("php://stderr", "w"), "PATH_INFO : $path_info\n");

// Vérifier que PATH_INFO contient une chaîne de requête après le "?".
if (strpos($path_info, '?') !== false) {
    // Extraire la partie après le "?".
    $query_string = substr($path_info, strpos($path_info, '?') + 1);

    // Analyser la chaîne de requête.
    parse_str($query_string, $params);

    // Extraire le login à partir des paramètres
    $login = isset($params['login']) ? htmlspecialchars($params['login']) : 'Non fourni';
} else {
    $login = 'Non fourni';
}

// Afficher le login pour débogage
fwrite(fopen("php://stderr", "w"), "Login extrait : $login\n");

// Construire le corps de la réponse HTML
$body = "<html>
<head>
    <title>Data received</title>
</head>
<body style=\"font-family: Arial, sans-serif; padding: 20px;\">
    <h1>Data received from GET request</h1>
    <p><strong>Login:</strong> $login</p>
    <hr>
    <p><em>This is a response generated by the PHP script.</em></p>
</body>
</html>";

// Construire les en-têtes HTTP
$header = "HTTP/1.1 200 OK\r\n";
$header .= "Content-Type: text/html\r\n";
$header .= "Content-Length: " . strlen($body) . "\r\n";
$header .= "\r\n";

// Envoyer la réponse HTTP complète
echo $header . $body;

exit(0);
?>
