<?php
ini_set('default_mimetype', '');

// Récupérer le PATH_INFO depuis les variables d'environnement CGI
$path_info = getenv('PATH_INFO');

// Afficher le PATH_INFO pour débogage
fwrite(fopen("php://stderr", "w"), "PATH_INFO : $path_info\n");

// Vérifier que PATH_INFO contient une chaîne de requête après le "?".
if (strpos($path_info, '?') !== false) {
    // Extraire la partie après le "?".
    $query_string = substr($path_info, strpos($path_info, '?') + 1);

    // Analyser la chaîne de requête.
    parse_str($query_string, $params);

    // Extraire le login à partir des paramètres
    $login = isset($params['login']) ? htmlspecialchars($params['login']) : 'Non fourni';
} else {
    $login = 'Non fourni';
}

// Afficher le login pour débogage
fwrite(fopen("php://stderr", "w"), "Login extrait : $login\n");

$url = "https://webservcgi-default-rtdb.europe-west1.firebasedatabase.app/users/{$login}.json";

$response = file_get_contents($url);

// Vérifier si la requête a réussi
if ($response === FALSE) {
	die('Error occurred while fetching data');
}
file_put_contents('response_log.txt', $response);

// Décoder la réponse JSON
$user_data = json_decode($response, true);

if (isset($user_data['login']) && $user_data['login'] === $login) {
    // Si le login correspond, extraire les autres informations
    $email = $user_data['email'];
    $first_name = $user_data['first_name'];
    $last_name = $user_data['last_name'];
    $pet = isset($user_data['pet name']) ? $user_data['pet name'] : 'No pet information';

    // Construire le corps de la réponse HTML avec les informations récupérées
    $body = "<html>
    <head>
        <title>Data received</title>
    </head>
    <body style=\"font-family: Arial, sans-serif; padding: 20px;\">
        <h1>User Information</h1>
        <p><strong>Login:</strong> $login</p>
        <p><strong>Email:</strong> $email</p>
        <p><strong>First Name:</strong> $first_name</p>
        <p><strong>Last Name:</strong> $last_name</p>
        <p><strong>Pet Name:</strong> $pet</p>
        <hr>
        <p><em>This is a response generated by the PHP script.</em></p>
    </body>
    </html>";
} else {
    // Si le login ne correspond pas, afficher un message d'erreur
    $body = "<html>
    <head>
        <title>Error</title>
    </head>
    <body style=\"font-family: Arial, sans-serif; padding: 20px;\">
        <h1>User not found</h1>
        <p>The login <strong>$login</strong> does not match any user.</p>
        <hr>
        <p><em>This is a response generated by the PHP script.</em></p>
    </body>
    </html>";
}
// Construire les en-têtes HTTP
$header = "HTTP/1.1 200 OK\r\n";
$header .= "Content-Type: text/html\r\n";
$header .= "Content-Length: " . strlen($body) . "\r\n";
$header .= "\r\n";

// Envoyer la réponse HTTP complète
echo $header . $body;

exit(0);
?>
