<?php
ini_set('default_mimetype', '');

// Lire tout le corps de la requête depuis l'entrée standard
$rawInput = file_get_contents("php://stdin");

// Écrire l'entrée brute dans la sortie d'erreur pour débogage (facultatif)
fwrite(fopen("php://stderr", "w"), "Données brutes : $rawInput\n");

// Parser les données reçues si elles sont au format application/x-www-form-urlencoded
parse_str($rawInput, $postData);

// Récupérer les valeurs des champs
$firstName = isset($postData['first_name']) ? htmlspecialchars($postData['first_name']) : 'Non fourni';
$lastName = isset($postData['last_name']) ? htmlspecialchars($postData['last_name']) : 'Non fourni';
$login = isset($postData['login']) ? htmlspecialchars($postData['login']) : 'Non fourni';
$anecdote = isset($postData['anecdote']) ? htmlspecialchars($postData['anecdote']) : 'Non fourni';

// Construire le corps de la réponse HTML
$body = "<html>
<head>
    <title>data received</title>
</head>
<body style=\"font-family: Arial, sans-serif; padding: 20px;\">
    <h1>data received from form</h1>
    <p><strong>first name :</strong> $firstName</p>
    <p><strong>Name :</strong> $lastName</p>
    <p><strong>Login :</strong> $login</p>
    <p><strong>story :</strong> $anecdote</p>
    <hr>
    <p><em>This is a response generated by the PHP script.</em></p>
</body>
</html>";

// Construire les en-têtes HTTP
$header = "HTTP/1.1 200 OK\r\n";
$header .= "Content-Type: text/html\r\n";
$header .= "Content-Length: " . strlen($body) . "\r\n";
$header .= "\r\n";

// Envoyer la réponse HTTP complète
echo $header . $body;
exit(0);
?>
