<?php
ini_set('default_mimetype', '');

// Lire tout le corps de la requête depuis l'entrée standard
$rawInput = file_get_contents("php://stdin");

// Écrire l'entrée brute dans la sortie d'erreur pour débogage (facultatif)
fwrite(fopen("php://stderr", "w"), "Données brutes : $rawInput\n");

// Parser les données reçues si elles sont au format application/x-www-form-urlencoded
parse_str($rawInput, $postData);

// Récupérer les valeurs des champs
$firstName = isset($postData['first_name']) ? htmlspecialchars($postData['first_name']) : 'Non fourni';
$lastName = isset($postData['last_name']) ? htmlspecialchars($postData['last_name']) : 'Non fourni';
$login = isset($postData['login']) ? htmlspecialchars($postData['login']) : 'Non fourni';
$anecdote = isset($postData['anecdote']) ? htmlspecialchars($postData['anecdote']) : 'Non fourni';


$url = "https://webservcgi-default-rtdb.europe-west1.firebasedatabase.app/users/{$login}.json";


$data = [
	'first_name' => $firstName,
	'last_name' => $lastName,
	'login' => $login,
	'anecdote' => $anecdote
];

// Convertir les données en JSON
$json_data = json_encode($data);


$options = [
    'http' => [
        'method'  => 'PUT',
        'header'  => "Content-Type: application/json\r\n" .
                     "Content-Length: " . strlen($json_data) . "\r\n",
        'content' => $json_data
    ]
];

$context = stream_context_create($options);

// Effectuer la requête PUT
$response = file_get_contents($url, false, $context);

// Vérifier si la requête a réussi
if ($response === FALSE) {
    die('Error occurred while sending PUT request');
}

// Décoder la réponse JSON
$response_data = json_decode($response, true);

// Construire le corps de la réponse HTML
$body = "<html>
<head>
    <title>Data updated</title>
</head>
<body style=\"font-family: Arial, sans-serif; padding: 20px;\">
    <h1>User Information Updated</h1>
    <p><strong>Login:</strong> $login</p>
    <p><strong>Name:</strong> " . $response_data['first_name'] . "</p>
    <p><strong>Anecdote:</strong> " . (isset($response_data['anecdote']) ? $response_data['anecdote'] : 'No pet information') . "</p>
    <hr>
    <p><em>This is a response generated by the PHP script.</em></p>
</body>
</html>";

// Construire les en-têtes HTTP
$header = "HTTP/1.1 200 OK\r\n";
$header .= "Content-Type: text/html\r\n";
$header .= "Content-Length: " . strlen($body) . "\r\n";
$header .= "\r\n";

// Envoyer la réponse HTTP complète
echo $header . $body;
exit(0);
?>

